all:
  vars:
    ansible_user: root
    project_name: mmaudio
    repo_path: /workspace/MMAudio
    remote_project_root: /home/docker/MMAudio
    image_repo: registry.ttd/mmaudio/mmaudio
    compose_file: compose.deploy.yaml
    ci_cache_ref: registry.ttd/mmaudio/mmaudio:buildcache
    ci_builder_name: default
    ci_platform: linux/amd64
    ci_push_latest: true
  children:
    build:
      hosts:
        ttd_nest:
          ansible_host: ttd-nest
    prod:
      hosts:
        mmaudio_prod:
          ansible_host: ttd-worker
          mmaudio_gpu_id: "0"
          mmaudio_port: "7860"
          mmaudio_domains:
            - mmaudio
            - mmaudio-api
          ingress_probe_host: ttd_nest
